name 'lamp'
maintainer 'Artemii Kropachev'
maintainer_email 'artemi.kropachev@li9.com'
license 'all_rights'
description 'Installs/Configures lamp'
long_description 'Installs/Configures lamp'
issues_url 'example.com'
source_url 'example.com'
version '1.0.1'

depends 'firewall', '~> 2.4.0'
depends 'chef-sugar', '>= 0.0.0'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.3.4'
depends 'mysql', '~> 7.1.1'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
